-- migrate:up

-- Reference data required in every environment. Names are canonical English;
-- the iOS app localizes them by slug (countries by ISO code).

INSERT INTO countries (code, name) VALUES
    ('BR', 'Brazil'), ('CO', 'Colombia'), ('PE', 'Peru'), ('EC', 'Ecuador'), ('BO', 'Bolivia'),
    ('VE', 'Venezuela'), ('MX', 'Mexico'), ('GT', 'Guatemala'), ('HN', 'Honduras'), ('SV', 'El Salvador'),
    ('NI', 'Nicaragua'), ('CR', 'Costa Rica'), ('PA', 'Panama'), ('JM', 'Jamaica'), ('DO', 'Dominican Republic'),
    ('CU', 'Cuba'), ('HT', 'Haiti'), ('PR', 'Puerto Rico'), ('US', 'United States'), ('ET', 'Ethiopia'),
    ('KE', 'Kenya'), ('TZ', 'Tanzania'), ('UG', 'Uganda'), ('RW', 'Rwanda'), ('BI', 'Burundi'),
    ('CD', 'DR Congo'), ('MW', 'Malawi'), ('ZM', 'Zambia'), ('ZW', 'Zimbabwe'), ('CM', 'Cameroon'),
    ('CI', 'Côte d''Ivoire'), ('MG', 'Madagascar'), ('YE', 'Yemen'), ('IN', 'India'), ('ID', 'Indonesia'),
    ('VN', 'Vietnam'), ('TH', 'Thailand'), ('LA', 'Laos'), ('MM', 'Myanmar'), ('CN', 'China'),
    ('PH', 'Philippines'), ('TL', 'Timor-Leste'), ('PG', 'Papua New Guinea'), ('AU', 'Australia'), ('TW', 'Taiwan'),
    ('NP', 'Nepal');

INSERT INTO varietals (slug, name, species) VALUES
    ('typica', 'Typica', 'arabica'),
    ('bourbon', 'Bourbon', 'arabica'),
    ('yellow_bourbon', 'Yellow Bourbon', 'arabica'),
    ('pink_bourbon', 'Pink Bourbon', 'arabica'),
    ('caturra', 'Caturra', 'arabica'),
    ('catuai', 'Catuai', 'arabica'),
    ('castillo', 'Castillo', 'arabica'),
    ('colombia', 'Colombia', 'arabica'),
    ('cenicafe_1', 'Cenicafé 1', 'arabica'),
    ('tabi', 'Tabi', 'arabica'),
    ('geisha', 'Geisha', 'arabica'),
    ('sl28', 'SL28', 'arabica'),
    ('sl34', 'SL34', 'arabica'),
    ('ruiru_11', 'Ruiru 11', 'arabica'),
    ('batian', 'Batian', 'arabica'),
    ('pacamara', 'Pacamara', 'arabica'),
    ('pacas', 'Pacas', 'arabica'),
    ('maragogype', 'Maragogype', 'arabica'),
    ('mundo_novo', 'Mundo Novo', 'arabica'),
    ('villa_sarchi', 'Villa Sarchi', 'arabica'),
    ('sidra', 'Sidra', 'arabica'),
    ('wush_wush', 'Wush Wush', 'arabica'),
    ('java', 'Java', 'arabica'),
    ('laurina', 'Laurina', 'arabica'),
    ('mokka', 'Mokka', 'arabica'),
    ('ethiopian_landrace', 'Ethiopian Landrace', 'arabica'),
    ('catimor', 'Catimor', 'arabica'),
    ('sarchimor', 'Sarchimor', 'arabica'),
    ('parainema', 'Parainema', 'arabica'),
    ('marsellesa', 'Marsellesa', 'arabica'),
    ('obata', 'Obatã', 'arabica'),
    ('icatu', 'Icatu', 'arabica'),
    ('centroamericano', 'Centroamericano (H1)', 'arabica'),
    ('chiroso', 'Chiroso', 'arabica'),
    ('robusta', 'Robusta', 'robusta'),
    ('liberica', 'Liberica', 'liberica'),
    ('excelsa', 'Excelsa', 'liberica');

INSERT INTO processing_methods (slug, name, description) VALUES
    ('washed', 'Washed', 'Fruit removed before drying; clean and bright cups.'),
    ('natural', 'Natural', 'Whole cherries dried with the fruit on; fruity and heavy-bodied.'),
    ('honey', 'Honey', 'Skin removed, part of the mucilage left on while drying.'),
    ('white_honey', 'White Honey', 'Honey process with very little mucilage left.'),
    ('yellow_honey', 'Yellow Honey', 'Honey process with a light layer of mucilage.'),
    ('red_honey', 'Red Honey', 'Honey process with most of the mucilage left.'),
    ('black_honey', 'Black Honey', 'Honey process with nearly all of the mucilage left.'),
    ('semi_washed', 'Semi-washed', 'Partially washed, dried with some mucilage.'),
    ('wet_hulled', 'Wet-hulled', 'Parchment removed while still wet (Giling Basah).'),
    ('anaerobic_natural', 'Anaerobic Natural', 'Whole cherries fermented without oxygen, then dried.'),
    ('anaerobic_washed', 'Anaerobic Washed', 'Depulped coffee fermented without oxygen, then washed.'),
    ('anaerobic_honey', 'Anaerobic Honey', 'Oxygen-free fermentation followed by honey drying.'),
    ('carbonic_maceration', 'Carbonic Maceration', 'Fermentation in a CO2-rich sealed tank.'),
    ('double_fermentation', 'Double Fermentation', 'Two consecutive fermentation stages.'),
    ('extended_fermentation', 'Extended Fermentation', 'Fermentation well beyond the usual duration.'),
    ('thermal_shock', 'Thermal Shock', 'Alternating hot and cold water baths after fermentation.'),
    ('co_fermented', 'Co-fermented', 'Fermented together with fruit, spices or other additions.'),
    ('yeast_inoculated', 'Yeast Inoculated', 'Fermentation driven by selected yeast strains.'),
    ('koji', 'Koji', 'Fermentation with Aspergillus oryzae (koji).'),
    ('experimental', 'Experimental', 'Any other experimental processing.');

INSERT INTO brew_methods
    (slug, name, category, ratio_basis, description, default_ratio, default_grind_size, default_water_temp_c, sort_order)
VALUES
    ('v60', 'V60', 'pour_over', 'water', 'Conical dripper with spiral ribs and a large single hole.', 16.0, 'medium_fine', 93, 10),
    ('chemex', 'Chemex', 'pour_over', 'water', 'Glass brewer with thick bonded paper filters.', 16.0, 'medium_coarse', 94, 20),
    ('kalita_wave', 'Kalita Wave', 'pour_over', 'water', 'Flat-bottom dripper with three small holes.', 16.0, 'medium', 93, 30),
    ('origami', 'Origami', 'pour_over', 'water', 'Ceramic dripper that accepts conical and wave filters.', 16.0, 'medium_fine', 93, 40),
    ('melitta', 'Melitta', 'pour_over', 'water', 'Classic wedge-shaped dripper.', 16.0, 'medium', 93, 50),
    ('cloth_filter', 'Cloth Filter', 'pour_over', 'water', 'Traditional cloth-sock filter (chorreador).', 15.0, 'medium', 92, 60),
    ('french_press', 'French Press', 'immersion', 'water', 'Full immersion with a metal mesh plunger.', 15.0, 'coarse', 94, 70),
    ('clever_dripper', 'Clever Dripper', 'immersion', 'water', 'Immersion dripper with a release valve.', 16.0, 'medium', 94, 80),
    ('hario_switch', 'Hario Switch', 'immersion', 'water', 'V60-style dripper with an immersion switch.', 16.0, 'medium_fine', 93, 90),
    ('siphon', 'Siphon', 'immersion', 'water', 'Vacuum brewer heated from below.', 15.0, 'medium', 92, 100),
    ('cupping', 'Cupping', 'immersion', 'water', 'SCA cupping protocol (8.25 g per 150 ml).', 18.2, 'medium_coarse', 93, 110),
    ('aeropress', 'AeroPress', 'pressure', 'water', 'Immersion brewer finished with hand pressure.', 14.0, 'medium_fine', 90, 120),
    ('moka_pot', 'Moka Pot', 'pressure', 'water', 'Stovetop brewer pushed by steam pressure.', 10.0, 'fine', NULL, 130),
    ('espresso', 'Espresso', 'espresso', 'beverage', 'Machine-pressurized extraction, ratio by beverage weight.', 2.0, 'fine', 93, 140),
    ('turkish', 'Turkish Coffee', 'other', 'water', 'Very fine coffee simmered in a cezve.', 10.0, 'extra_fine', NULL, 150),
    ('cold_brew', 'Cold Brew', 'cold_brew', 'water', 'Long steep in cold or room-temperature water.', 8.0, 'coarse', 20, 160),
    ('cold_drip', 'Cold Drip', 'cold_brew', 'water', 'Slow ice-water drip (Kyoto style).', 10.0, 'medium', NULL, 170),
    ('batch_brew', 'Batch Brew', 'drip_machine', 'water', 'Automatic drip coffee machine.', 16.0, 'medium', 93, 180);

INSERT INTO grinders (slug, brand, model, kind, burr_type) VALUES
    ('comandante_c40_mk4', 'Comandante', 'C40 MK4', 'manual', 'conical'),
    ('1zpresso_jx_pro', '1Zpresso', 'JX-Pro', 'manual', 'conical'),
    ('1zpresso_k_ultra', '1Zpresso', 'K-Ultra', 'manual', 'conical'),
    ('1zpresso_zp6_special', '1Zpresso', 'ZP6 Special', 'manual', 'conical'),
    ('timemore_c2', 'Timemore', 'Chestnut C2', 'manual', 'conical'),
    ('timemore_c3', 'Timemore', 'Chestnut C3', 'manual', 'conical'),
    ('kingrinder_k6', 'Kingrinder', 'K6', 'manual', 'conical'),
    ('hario_skerton_pro', 'Hario', 'Skerton Pro', 'manual', 'conical'),
    ('porlex_mini_2', 'Porlex', 'Mini II', 'manual', 'conical'),
    ('baratza_encore_esp', 'Baratza', 'Encore ESP', 'electric', 'conical'),
    ('baratza_virtuoso_plus', 'Baratza', 'Virtuoso+', 'electric', 'conical'),
    ('baratza_sette_270', 'Baratza', 'Sette 270', 'electric', 'conical'),
    ('fellow_ode_gen2', 'Fellow', 'Ode Gen 2', 'electric', 'flat'),
    ('niche_zero', 'Niche', 'Zero', 'electric', 'conical'),
    ('df64', 'Turin', 'DF64', 'electric', 'flat'),
    ('eureka_mignon_specialita', 'Eureka', 'Mignon Specialità', 'electric', 'flat'),
    ('mahlkonig_ek43', 'Mahlkönig', 'EK43', 'electric', 'flat'),
    ('wilfa_uniform', 'Wilfa', 'Svart Uniform', 'electric', 'flat'),
    ('breville_smart_grinder_pro', 'Breville', 'Smart Grinder Pro', 'electric', 'conical'),
    ('lagom_p64', 'Option-O', 'Lagom P64', 'electric', 'flat');

INSERT INTO flavor_notes (slug, name, category) VALUES
    ('blackberry', 'Blackberry', 'fruity'),
    ('raspberry', 'Raspberry', 'fruity'),
    ('blueberry', 'Blueberry', 'fruity'),
    ('strawberry', 'Strawberry', 'fruity'),
    ('raisin', 'Raisin', 'fruity'),
    ('prune', 'Prune', 'fruity'),
    ('coconut', 'Coconut', 'fruity'),
    ('cherry', 'Cherry', 'fruity'),
    ('pomegranate', 'Pomegranate', 'fruity'),
    ('pineapple', 'Pineapple', 'fruity'),
    ('grape', 'Grape', 'fruity'),
    ('apple', 'Apple', 'fruity'),
    ('peach', 'Peach', 'fruity'),
    ('pear', 'Pear', 'fruity'),
    ('grapefruit', 'Grapefruit', 'fruity'),
    ('orange', 'Orange', 'fruity'),
    ('lemon', 'Lemon', 'fruity'),
    ('lime', 'Lime', 'fruity'),
    ('tropical_fruit', 'Tropical Fruit', 'fruity'),
    ('black_tea', 'Black Tea', 'floral'),
    ('chamomile', 'Chamomile', 'floral'),
    ('rose', 'Rose', 'floral'),
    ('jasmine', 'Jasmine', 'floral'),
    ('bergamot', 'Bergamot', 'floral'),
    ('brown_sugar', 'Brown Sugar', 'sweet'),
    ('panela', 'Panela', 'sweet'),
    ('molasses', 'Molasses', 'sweet'),
    ('maple_syrup', 'Maple Syrup', 'sweet'),
    ('caramel', 'Caramel', 'sweet'),
    ('honey', 'Honey', 'sweet'),
    ('vanilla', 'Vanilla', 'sweet'),
    ('hazelnut', 'Hazelnut', 'nutty_cocoa'),
    ('almond', 'Almond', 'nutty_cocoa'),
    ('peanut', 'Peanut', 'nutty_cocoa'),
    ('milk_chocolate', 'Milk Chocolate', 'nutty_cocoa'),
    ('dark_chocolate', 'Dark Chocolate', 'nutty_cocoa'),
    ('cocoa', 'Cocoa', 'nutty_cocoa'),
    ('cinnamon', 'Cinnamon', 'spices'),
    ('clove', 'Clove', 'spices'),
    ('nutmeg', 'Nutmeg', 'spices'),
    ('anise', 'Anise', 'spices'),
    ('black_pepper', 'Black Pepper', 'spices'),
    ('cereal', 'Cereal', 'roasted'),
    ('malt', 'Malt', 'roasted'),
    ('tobacco', 'Tobacco', 'roasted'),
    ('smoky', 'Smoky', 'roasted'),
    ('winey', 'Winey', 'sour_fermented'),
    ('whiskey', 'Whiskey', 'sour_fermented'),
    ('fermented', 'Fermented', 'sour_fermented'),
    ('herbal', 'Herbal', 'green_vegetative'),
    ('fresh_herbs', 'Fresh Herbs', 'green_vegetative');

-- migrate:down

DELETE FROM flavor_notes;
DELETE FROM grinders;
DELETE FROM brew_methods;
DELETE FROM processing_methods;
DELETE FROM varietals;
DELETE FROM countries;
