import BrewlyCore
import Foundation

public struct RecipeStepDTO: Codable, Sendable, Equatable, Hashable {
    /// 1-based order of the step.
    public var position: Int
    public var kind: BrewStepKind
    /// Second at which the step starts.
    public var startS: Int
    /// Cumulative scale reading to reach during the step.
    public var waterTargetG: Double?
    public var instruction: String?

    public init(position: Int, kind: BrewStepKind, startS: Int, waterTargetG: Double? = nil, instruction: String? = nil) {
        self.position = position
        self.kind = kind
        self.startS = startS
        self.waterTargetG = waterTargetG
        self.instruction = instruction
    }
}

/// A step in a create/update request; its position is its index in the array.
public struct RecipeStepInput: Codable, Sendable, Equatable, Hashable {
    public var kind: BrewStepKind
    public var startS: Int
    public var waterTargetG: Double?
    public var instruction: String?

    public init(kind: BrewStepKind, startS: Int, waterTargetG: Double? = nil, instruction: String? = nil) {
        self.kind = kind
        self.startS = startS
        self.waterTargetG = waterTargetG
        self.instruction = instruction
    }
}

/// A full recipe (a preparation) with every brewing parameter.
public struct RecipeDTO: Codable, Sendable, Equatable, Hashable {
    public var id: UUID
    public var author: UserSummaryDTO
    public var bean: BeanSummaryDTO
    public var methodSlug: String
    public var forkedFromId: UUID?
    /// The original recipe of a remix; `nil` when it is gone or the viewer can't see it.
    public var forkedFrom: RecipeReferenceDTO?
    public var title: String
    public var description: String?
    public var doseG: Double
    public var waterG: Double?
    public var yieldG: Double?
    /// Generated by the database: brew water (or beverage) / dose.
    public var ratio: Double
    public var grindSize: GrindSize
    public var grinderSlug: String?
    public var grindSetting: String?
    public var grindMicrons: Int?
    public var waterTempC: Double?
    public var bloomWaterG: Double?
    public var bloomTimeS: Int?
    public var totalTimeS: Int?
    public var pressureBar: Double?
    public var filterType: FilterType?
    public var waterProfile: String?
    public var waterTdsPpm: Int?
    public var tdsPercent: Double?
    /// Generated by the database: beverage × TDS% / dose.
    public var extractionYieldPercent: Double?
    public var rating: Int?
    public var notes: String?
    public var flavorNoteSlugs: [String]
    public var steps: [RecipeStepDTO]
    public var visibility: Visibility
    /// How many people saved the recipe.
    public var saveCount: Int
    /// How many remixes were made from the recipe.
    public var forkCount: Int
    /// Whether the viewer saved the recipe.
    public var isSaved: Bool
    public var createdAt: Date
    public var updatedAt: Date

    public init(
        id: UUID,
        author: UserSummaryDTO,
        bean: BeanSummaryDTO,
        methodSlug: String,
        forkedFromId: UUID? = nil,
        forkedFrom: RecipeReferenceDTO? = nil,
        title: String,
        description: String? = nil,
        doseG: Double,
        waterG: Double? = nil,
        yieldG: Double? = nil,
        ratio: Double,
        grindSize: GrindSize,
        grinderSlug: String? = nil,
        grindSetting: String? = nil,
        grindMicrons: Int? = nil,
        waterTempC: Double? = nil,
        bloomWaterG: Double? = nil,
        bloomTimeS: Int? = nil,
        totalTimeS: Int? = nil,
        pressureBar: Double? = nil,
        filterType: FilterType? = nil,
        waterProfile: String? = nil,
        waterTdsPpm: Int? = nil,
        tdsPercent: Double? = nil,
        extractionYieldPercent: Double? = nil,
        rating: Int? = nil,
        notes: String? = nil,
        flavorNoteSlugs: [String] = [],
        steps: [RecipeStepDTO] = [],
        visibility: Visibility = .public,
        saveCount: Int = 0,
        forkCount: Int = 0,
        isSaved: Bool = false,
        createdAt: Date,
        updatedAt: Date
    ) {
        self.id = id
        self.author = author
        self.bean = bean
        self.methodSlug = methodSlug
        self.forkedFromId = forkedFromId
        self.forkedFrom = forkedFrom
        self.title = title
        self.description = description
        self.doseG = doseG
        self.waterG = waterG
        self.yieldG = yieldG
        self.ratio = ratio
        self.grindSize = grindSize
        self.grinderSlug = grinderSlug
        self.grindSetting = grindSetting
        self.grindMicrons = grindMicrons
        self.waterTempC = waterTempC
        self.bloomWaterG = bloomWaterG
        self.bloomTimeS = bloomTimeS
        self.totalTimeS = totalTimeS
        self.pressureBar = pressureBar
        self.filterType = filterType
        self.waterProfile = waterProfile
        self.waterTdsPpm = waterTdsPpm
        self.tdsPercent = tdsPercent
        self.extractionYieldPercent = extractionYieldPercent
        self.rating = rating
        self.notes = notes
        self.flavorNoteSlugs = flavorNoteSlugs
        self.steps = steps
        self.visibility = visibility
        self.saveCount = saveCount
        self.forkCount = forkCount
        self.isSaved = isSaved
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }
}

/// A link to another recipe, e.g. the original of a remix.
public struct RecipeReferenceDTO: Codable, Sendable, Equatable, Hashable {
    public var id: UUID
    public var title: String
    public var author: UserSummaryDTO

    public init(id: UUID, title: String, author: UserSummaryDTO) {
        self.id = id
        self.title = title
        self.author = author
    }
}

/// Response of `PUT` and `DELETE /recipes/{id}/save`.
public struct SaveStateDTO: Codable, Sendable, Equatable {
    public var isSaved: Bool
    public var saveCount: Int

    public init(isSaved: Bool, saveCount: Int) {
        self.isSaved = isSaved
        self.saveCount = saveCount
    }
}

/// Compact recipe used in lists.
public struct RecipeSummaryDTO: Codable, Sendable, Equatable, Hashable {
    public var id: UUID
    public var author: UserSummaryDTO
    public var beanName: String
    public var methodSlug: String
    public var title: String
    public var doseG: Double
    public var ratio: Double
    public var grindSize: GrindSize
    public var waterTempC: Double?
    public var totalTimeS: Int?
    public var rating: Int?
    public var visibility: Visibility
    public var createdAt: Date

    public init(
        id: UUID,
        author: UserSummaryDTO,
        beanName: String,
        methodSlug: String,
        title: String,
        doseG: Double,
        ratio: Double,
        grindSize: GrindSize,
        waterTempC: Double? = nil,
        totalTimeS: Int? = nil,
        rating: Int? = nil,
        visibility: Visibility = .public,
        createdAt: Date
    ) {
        self.id = id
        self.author = author
        self.beanName = beanName
        self.methodSlug = methodSlug
        self.title = title
        self.doseG = doseG
        self.ratio = ratio
        self.grindSize = grindSize
        self.waterTempC = waterTempC
        self.totalTimeS = totalTimeS
        self.rating = rating
        self.visibility = visibility
        self.createdAt = createdAt
    }
}

/// Body of `POST /recipes` and `PUT /recipes/{id}`.
public struct UpsertRecipeRequest: Codable, Sendable, Equatable {
    public var beanId: UUID
    /// The recipe this one remixes. Only read on create; the viewer must be able to see it.
    public var forkedFromId: UUID?
    public var methodSlug: String
    public var title: String
    public var description: String?
    public var doseG: Double
    public var waterG: Double?
    public var yieldG: Double?
    public var grindSize: GrindSize
    public var grinderSlug: String?
    public var grindSetting: String?
    public var grindMicrons: Int?
    public var waterTempC: Double?
    public var bloomWaterG: Double?
    public var bloomTimeS: Int?
    public var totalTimeS: Int?
    public var pressureBar: Double?
    public var filterType: FilterType?
    public var waterProfile: String?
    public var waterTdsPpm: Int?
    public var tdsPercent: Double?
    public var rating: Int?
    public var notes: String?
    public var flavorNoteSlugs: [String]
    public var steps: [RecipeStepInput]
    public var visibility: Visibility

    public init(
        beanId: UUID,
        forkedFromId: UUID? = nil,
        methodSlug: String,
        title: String,
        description: String? = nil,
        doseG: Double,
        waterG: Double? = nil,
        yieldG: Double? = nil,
        grindSize: GrindSize,
        grinderSlug: String? = nil,
        grindSetting: String? = nil,
        grindMicrons: Int? = nil,
        waterTempC: Double? = nil,
        bloomWaterG: Double? = nil,
        bloomTimeS: Int? = nil,
        totalTimeS: Int? = nil,
        pressureBar: Double? = nil,
        filterType: FilterType? = nil,
        waterProfile: String? = nil,
        waterTdsPpm: Int? = nil,
        tdsPercent: Double? = nil,
        rating: Int? = nil,
        notes: String? = nil,
        flavorNoteSlugs: [String] = [],
        steps: [RecipeStepInput] = [],
        visibility: Visibility = .public
    ) {
        self.beanId = beanId
        self.forkedFromId = forkedFromId
        self.methodSlug = methodSlug
        self.title = title
        self.description = description
        self.doseG = doseG
        self.waterG = waterG
        self.yieldG = yieldG
        self.grindSize = grindSize
        self.grinderSlug = grinderSlug
        self.grindSetting = grindSetting
        self.grindMicrons = grindMicrons
        self.waterTempC = waterTempC
        self.bloomWaterG = bloomWaterG
        self.bloomTimeS = bloomTimeS
        self.totalTimeS = totalTimeS
        self.pressureBar = pressureBar
        self.filterType = filterType
        self.waterProfile = waterProfile
        self.waterTdsPpm = waterTdsPpm
        self.tdsPercent = tdsPercent
        self.rating = rating
        self.notes = notes
        self.flavorNoteSlugs = flavorNoteSlugs
        self.steps = steps
        self.visibility = visibility
    }

    /// The fields checked by `RecipeRules`.
    public var parameters: RecipeParameters {
        RecipeParameters(
            title: title,
            description: description,
            doseG: doseG,
            waterG: waterG,
            yieldG: yieldG,
            grindSetting: grindSetting,
            grindMicrons: grindMicrons,
            waterTempC: waterTempC,
            bloomWaterG: bloomWaterG,
            bloomTimeS: bloomTimeS,
            totalTimeS: totalTimeS,
            pressureBar: pressureBar,
            waterProfile: waterProfile,
            waterTdsPpm: waterTdsPpm,
            tdsPercent: tdsPercent,
            rating: rating,
            notes: notes,
            steps: steps.map {
                RecipeParameters.Step(startS: $0.startS, waterTargetG: $0.waterTargetG, instruction: $0.instruction)
            }
        )
    }
}
